using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LanguageEnum : MonoBehaviour
{
    public enum Languages
    {
        English,
        Afrikaans,
        Albanian,
        Amharic,
        Arabic,
        Armenian,
        Assamese,
        Aymara,
        Azerbaijani,
        Bambara,
        Bashkir,
        Basque,
        Belarusian,
        Bengali,
        Bhojpuri,
        Bosnian,
        Bulgarian,
        Cantonese,
        Catalan,
        Cebuano,
        Chichewa,
        Chinese,
        Corsican,
        Croatian,
        Czech,
        Danish,
        Dari,
        Dhivehi,
        Dogri,
        Dutch,
        Esperanto,
        Estonian,
        Ewe,
        Faroese,
        Fijian,
        Filipino,
        Finnish,
        French,
        FrenchCanada,
        Frisian,
        Galician,
        Georgian,
        German,
        Greek,
        Guarani,
        Gujarati,
        HaitianCreole,
        Hausa,
        Hawaiian,
        Hebrew,
        Hindi,
        Hmong,
        Hungarian,
        Icelandic,
        Igbo,
        Ilocano,
        Indonesian,
        Inuinnaqtun,
        Inuktitut,
        Irish,
        Italian,
        Japanese,
        Javanese,
        Kannada,
        Kazakh,
        Khmer,
        Kinyarwanda,
        Konkoni,
        Korean,
        Krio,
        Kurdish,
        KurdishSorani,
        Kyrgyz,
        Lao,
        Latin,
        Latvian,
        Lingala,
        Lithuanian,
        Luganda,
        Luxembourgish,
        Macedonian,
        Maithili,
        Malagasy,
        Malay,
        Malayalam,
        Maltese,
        Maori,
        Marathi,
        Meiteilon,
        Mizo,
        Mongolian,
        MyanmarBurmese,
        Nepali,
        Norwegian,
        Nyanja,
        Odia,
        Oromo,
        Pashto,
        Persian,
        Polish,
        Portuguese,
        PortugueseBrazilian,
        Punjabi,
        Quechua,
        Queretaro,
        Romanian,
        Rundi,
        Russian,
        Samoan,
        Sanskrit,
        ScotsGaelic,
        Sepedi,
        Serbian,
        Sesotho,
        Setswana,
        Shona,
        Sindhi,
        Sinhala,
        Slovak,
        Slovenian,
        Somali,
        Spanish,
        Sundanese,
        Swahili,
        Swedish,
        Tajik,
        Tamil,
        Tatar,
        Telugu,
        Thai,
        Tibetan,
        Tigrinya,
        Tongan,
        Tsonga,
        Turkish,
        Turkmen,
        Twi,
        Ukrainian,
        UpperSorbian,
        Urdu,
        Uyghur,
        Uzbek,
        Vietnamese,
        Welsh,
        Xhosa,
        Yiddish,
        Yoruba,
        YucatecMaya,
        Zulu
    }

    public static string[] LanguageNames =
    {
        "English",
"Afrikaans",
"Albanian shqiptare",
"Amharic አማርኛ",
"Arabic عربي",
"Armenian հայերեն",
"Assamese অসমীয়া",
"Aymara ",
"Azerbaijan Azərbaycan",
"Bambara Bamanankan",
"Bashkir Башҡорттар",
"Basque euskara",
"Belarusian беларускі",
"Bengali বাংলা",
"Bhojpuri भोजपुरी",
"Bosnian bosanski",
"Bulgarian български",
"Cantonese 粵語",
"Catalan català",
"Cebuano ",
"Chichewa",
"Chinese (Simplified) 中国人",
"Corsican Corsu",
"Croatian Hrvatski",
"Czech čeština",
"Danish dansk",
"Dari دری",
"Divehi ދިވެހި...",
"Dogri डोगरी",
"Dutch Nederlands",
"Esperanto ",
"Estonian eesti keel",
"Ewe Eʋegbe",
"Faroese Føroyskt",
"Fijian Viti",
"Filipino ",
"Finnish Suomalainen",
"French Français",
"French Canadian Canadien français",
"Frisian Frysk",
"Galician galego",
"Georgian ქართული",
"German Deutsch",
"Greek Ελληνικά",
"Guarani ",
"Gujarati ગુજરાતી",
"Haitian Creole Kreyòl ayisyen",
"Hausa ",
"Hawaiian ʻŌlelo Hawaiʻi",
"Hebrew עִברִית",
"Hindi हिंदी",
"Hmong Hmoob",
"Hungarian Magyar",
"Icelandic íslenskur",
"Igbo ",
"Ilocano",
"Indonesian bahasa Indonesia",
"Inuinnaqtun ",
"Inuktitut ᐃᓄᒃᑎᑐᑦ",
"Irish Gaeilge",
"Italian Italiana",
"Japanese 日本",
"Javanese basa jawa",
"Kannada ಕನ್ನಡ",
"Kazakh қазақ",
"Khmer ខ្មែរ",
"Kinyarwanda ",
"Konkani कोंकणी",
"Korean 한국인",
"Krio ",
"Kurdish (Kurmanji) Kurdî (Kurmancî)",
"Kurdish (Sorani) کوردی (سۆرانی)",
"Kyrgyz Кыргызча",
"Lao ພາສາລາວ",
"Latin Latinus",
"Latvian latviski",
"Lingala ",
"Lithuanian lietuvių",
"Luganda Oluganda",
"Luxembourgish lëtzebuergesch",
"Macedonian македонски",
"Maithili मैथिली",
"Malagasy ",
"Malay Melayu",
"Malayalam മലയാളം",
"Maltese  Malti",
"Maori ",
"Marathi मराठी",
"Meiteilon (Manipuri) ꯃꯦꯏꯇꯦꯏꯂꯣꯟ (ꯃꯅꯤꯄꯨꯔꯤ) ꯴.",
"Mizo Mizo tawng",
"Mongolian Монгол",
"Myanmar (Burmese) မြန်မာ (ဗမာ)၊",
"Nepali नेपाली",
"Norwegian norsk",
"Nyanja ",
"Odia ଓଡିଆ",
"Oromo Afaan Oromoo",
"Pashto پښتو",
"Persian فارسی",
"Polish Polski",
"Portuguese Português",
"Portuguese Brazil Português do Brasil",
"Punjabi ਪੰਜਾਬੀ",
"Quechua Runasimi",
"Querétaro Maxei",
"Romanian Română",
"Rundi rundi rundi",
"Russian Русский",
"Samoan Samoa",
"Sanskrit संस्कृत",
"Scottish Gaelic Gàidhlig na h-Alba",
"Sepedi",
"Serbian Српски",
"Sesotho",
"Setswana",
"Shona ",
"Sindhi سنڌي",
"Sinhala සිංහල",
"Slovak slovenský",
"Slovenian Slovenščina",
"Somali Soomaali",
"Spanish Española",
"Sundanese basa Sunda",
"Swahili kiswahili",
"Swedish svenska",
"Tajik тоҷикӣ",
"Tamil தமிழ்",
"Tatar Татар",
"Telugu తెలుగు",
"Thai แบบไทย",
"Tibetan བོད་ཡིག",
"Tigrinya ትግሪኛ",
"Tongan Tonga",
"Tsonga",
"Turkish Türk",
"Turkmen Türkmenler",
"Twi ",
"Ukrainian українська ",
"Upper Sorbian Hornjoserbšćina",
"Urdu اردو",
"Uyghur ئۇيغۇر",
"Uzbek o'zbek",
"Vietnamese Tiếng Việt",
"Welsh Cymraeg",
"Xhosa isiXhosa",
"Yiddish יידיש",
"Yoruba ",
"Yucatec Maya",
"Zulu ",
    };
}
