using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LanguageEnum : MonoBehaviour
{
    public enum Languages
    {
        English,
        Afrikaans,
        Arabic,
        Bengali,
        Chinese,
        Croatian,
        Ewe,
        Filipino,
        French,
        Georgian,
        German,
        Greek,
        Gujarati,
        HaitianCreole,
        Hindi,
        Hmong,
        Igbo,
        Italian,
        Japanese,
        Kannada,
        Khmer,
        Kinyarwanda,
        Korean,
        Krio,
        KurdishKurmanji,
        KurdishSorani,
        Lao,
        Lingala,
        Luganda,
        Malay,
        Marathi,
        Malayalam,
        Nepali,
        Pashto,
        Persian,
        Polish,
        Portuguese,
        Quechua,
        Russian,
        Shona,
        Somali,
        Spanish,
        Swahili,
        Tamil,
        Telugu,
        Thai,
        Turkish,
        Twi,
        Ukrainian,
        Urdu,
        Vietnamese,
        Yoruba
    }

    public static string[] LanguageNames =
    {
        "English",
        "Afrikaans ",
        "Arabic عربي",
        "Bengali বাংলা",
        "Chinese 中国人",
        "Croatian Hrvatski",
        "Ewe Eʋegbe",
        "Filipino",
        "French Français",
        "Georgian ქართული",
        "German Deutsch",
        "Greek Ελληνικά",
        "Gujarati ગુજરાતી",
        "Haitian Creole Kreyòl Ayisyen",
        "Hindi हिन्दी",
        "Hmong Hmoob",
        "Igbo ",
        "Italian Italiana",
        "Japanese 日本",
        "Kannada ಕನ್ನಡ ",
        "Khmer  ",
        "Kinyarwandua ",
        "Korean 한국인",
        "Krio ",
        "Kurdish Kurmanji",
        "Kurdish Sorani کوردی سۆرانی",
        "Lao ລາວ",
        "Lingala",
        "Luganda Oluganda",
        "Malay Melayu",
        "Marathi मराठी",
        "Maylayalam മലയാളം",
        "Nepali नेपाली",
        "Pashto پښتو",
        "Persian فارسی",
        "Polish Polski",
        "Portuguese Português do Brasil",
        "Quechua Runasimi ",
        "Russian Русский",
        "Shona ",
        "Somali Somaliyeed",
        "Spanish Española",
        "Swahili Kiswahili",
        "Tamil தமிழ் ",
        "Telugu తెలుగు",
        "Thai  ไทย",
        "Turkish Türk",
        "Twi Akan",
        "Ukranian українська",
        "Urdu اردو",
        "Vietnamese Tiếng Việt",
        "Yoruba"
    };
}
